version: '3.8'

services:
  postgres:
    container_name: postgres
    image: ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db: